<?php if(!isset($_REQUEST['p']) || $_REQUEST['p']==""){ ?>





	<ul class="form"><div class="box_body">

	<br class="clear">	
	<div id="gallerycontent">
	<?php  
		$NOTALLOWED = array(".zip","html",".html",".php");
		$counter=1;  
		if ($handle = opendir(subd.'inc/templates/')) {
	   /* This is the correct way to loop over the directory. */
	   while (false !== ($file = readdir($handle))) {
			if($file == "admin1"){
			}elseif(substr($file,0,6) == "mobile"){
			}elseif($file == "."){
			}elseif($file == ".."){
			}elseif(in_array(substr($file,-4),$NOTALLOWED)){
			}elseif($file == "layout"){
			}else{   	
	?>
	
		<div class="thumb">
			<a href="template.php?do=template&newtemp=<?php print $file; ?>" rel="bookmark"><img src="<?=DB_DOMAIN ?>inc/templates/<?php print $file; ?>/images/design.gif"></a>
			<p class="themelabel" style="overflow:hidden;text-align:center;"><a href="#" onclick="return false;"><b><?=$file ?></b></a><br><br><a href="template.php?do=template&newtemp=<?php print $file; ?>"><?php if(D_TEMP == $file){ ?><font color="#FF0000"><strong><?=$admin_design[2] ?></strong></font><?php }else{ ?><?=$admin_design[3] ?><?php } ?></a></p>
		</div>	
	<?php 		}   }   closedir($handle); } ?>
	</div>	 
	</div> </ul>
	
	
		


<?php }elseif($_REQUEST['p'] =="meta"){ ?>

 
 
		<form method="post" action="template.php" name="form1">		
        <input name="do" type="hidden" value="metaedit" class="hidden">
		<input name="p" type="hidden" value="meta" class="hidden">
		<input name="change" id="change" type="hidden" value="single" class="hidden">
 


<ul class="form">
<div class="box_body">		
        <li><label>Custom Title Prefix: </label> <input name="m1" type="text" value="<?=SEO_PREFIX_TITLE ?>" class="input" style="width:470px;">
		<div class="tip">The title prefix will allow you to add your own text to the beginning of all title meta tags on your website. A sample prefix would be something like " My Website -"</div>
		</li>
        <li><label>Description Prefix: </label><textarea class="input" name="m2" style="width:470px; height:60px;"><?=SEO_PREFIX_DESC ?></textarea>
		<div class="tip">The description prefix will allow you to add your own text to the beginning of all description meta tags on your website. A sample prefix would be something like " Welcome to my website, "</div></li>
       	<li><label>Keyword Prefix: </label><textarea class="input" name="m3" style="width:470px; height:60px;"><?=SEO_PREFIX_KEYWORDS ?></textarea>
		<div class="tip">The title prefix will allow you to add your own text to the beginning of all keyword meta tags on your website. A sample prefix would be something like " my, website, "</div></li>
		
		<li><input type="submit" name="Submit" value="<?=$admin_button_val[8] ?>" class="MainBtn"></li>        
</div>
</ul>

<p id="TopCommentsBox">
<img align="absmiddle" src="inc/images/icons/help.png"/>
The home page is often the page many like to customize themselves and as content is not always generated by the system you can enter your own meta tags below.
</p>


 
<ul class="form"><div class="box_body">		
        <li><label>Page Title: </label> <input name="h1" type="text" value="<?=HOME_TITLE ?>" class="input" style="width:470px;">
		</li>
        <li><label><?=$admin_design[6] ?>: </label><textarea class="input" name="h2" style="width:470px; height:60px;"><?=HOME_DESC ?></textarea></li>
       	<li><label><?=$admin_design[7] ?>: </label><textarea class="input" name="h3" style="width:470px; height:60px;"><?=HOME_KEYWORDS ?></textarea></li>
		
		<li><input type="submit" name="Submit" value="<?=$admin_button_val[8] ?>" class="MainBtn"></li>        
	</div></ul>
      </form>
	

 

<?php }elseif($_REQUEST['p'] =="slider"){ ?>


<style>
.b1 { font-size:12px; font-weight:bold; color:#666666; }
</style> 

<ul class="form"><div class="box_body">
<form action="template.php" method="post" enctype="multipart/form-data" name="form2">
<input name="p" type="hidden" value="slider" class="hidden">
<input name="do" type="hidden" value="imgslider" id="do" class="hidden">
  <table width="100%"  border="0"  class="widefat">
   <thead> <tr>
      <th  scope="col">Image</th>
      <th  scope="col">&nbsp;</th>
    </tr></thead>
    <tr>
      <td>&nbsp;
<?php if(strlen(SLIDER1_IMAGE)  > 5){ ?>
<img src="<?=DB_DOMAIN.SLIDER1_IMAGE ?>" width=106 height="73"  onClick="PreviewWin('<?=DB_DOMAIN.SLIDER1_IMAGE ?>')">     
<?php }else{ ?>
no image set
<?php } ?>

 </td>
      <td><table width="100%"  border="0">
        <tr>
          <td class="b1">Title</td>
          <td><input name="st1" type="text" size="30" maxlength="200" value="<?=SLIDER1_TITLE ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Desc</td>
          <td><input name="sd1" type="text" size="30" maxlength="200" value="<?=SLIDER1_DESC ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Link </td>
          <td><input name="sl1" type="text" size="30" maxlength="200" value="<?=SLIDER1_LINK ?>" class="input"></td>
        </tr>
      </table>
        </td>
    </tr>
<tr>
	<td colspan="2">
	
	  <input type="file" name="file1" class="input">
	  Select a new image to replace this one 
	</td>
</tr>
    <tr>
      <td>&nbsp;
<?php if(strlen(SLIDER2_IMAGE)  > 5){ ?>
<img src="<?=DB_DOMAIN.SLIDER2_IMAGE ?>" width=106 height="73" onClick="PreviewWin('<?=DB_DOMAIN.SLIDER2_IMAGE ?>')">
<?php }else{ ?>
no image set
<?php } ?>

</td>
      <td><table width="100%"  border="0">
        <tr>
          <td class="b1">Title</td>
          <td><input name="st2" type="text" size="30" maxlength="200" value="<?=SLIDER2_TITLE ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Desc</td>
          <td><input name="sd2" type="text" size="30" maxlength="200" value="<?=SLIDER2_DESC ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Link </td>
          <td><input name="sl2" type="text" size="30" maxlength="200" value="<?=SLIDER2_LINK ?>" class="input"></td>
        </tr>
      </table></td>
    </tr>
<tr>
	<td colspan="2">
	
	  <input type="file" name="file2" class="input">
	  Select a new image to replace this one 
	</td>
</tr>
    <tr>
      <td>&nbsp;
<?php if(strlen(SLIDER3_IMAGE)  > 5){ ?>
<img src="<?=DB_DOMAIN.SLIDER3_IMAGE ?>" width=106 height="73" onClick="PreviewWin('<?=DB_DOMAIN.SLIDER3_IMAGE ?>')">

<?php }else{ ?>
no image set
<?php } ?>
</td>
      <td><table width="100%"  border="0">
        <tr>
          <td class="b1">Title</td>
          <td><input name="st3" type="text" size="30" maxlength="200" value="<?=SLIDER3_TITLE ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Desc</td>
          <td><input name="sd3" type="text" size="30" maxlength="200" value="<?=SLIDER3_DESC ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Link </td>
          <td><input name="sl3" type="text" size="30" maxlength="200" value="<?=SLIDER3_LINK ?>" class="input"></td>
        </tr>
      </table></td>
    </tr>
<tr>
	<td colspan="2">
	
	  <input type="file" name="file3" class="input">
	  Select a new image to replace this one 
	</td>
</tr>
    <tr>
      <td>&nbsp;
<?php if(strlen(SLIDER4_IMAGE)  > 5){ ?>
<img src="<?=DB_DOMAIN.SLIDER4_IMAGE ?>" width=106 height="73" onClick="PreviewWin('<?=DB_DOMAIN.SLIDER4_IMAGE ?>')">

<?php }else{ ?>
no image set
<?php } ?>
</td>
      <td><table width="100%"  border="0">
        <tr>
          <td class="b1">Title</td>
          <td><input name="st4" type="text" size="30" maxlength="200" value="<?=SLIDER4_TITLE ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Desc</td>
          <td><input name="sd4" type="text" size="30" maxlength="200" value="<?=SLIDER4_DESC ?>" class="input"></td>
        </tr>
        <tr>
          <td class="b1">Link </td>
          <td><input name="sl4" type="text" size="30" maxlength="200" value="<?=SLIDER4_LINK ?>" class="input"></td>
        </tr>
      </table></td>
    </tr>
<tr>
	<td colspan="2">
	
	  <input type="file" name="file4" class="input">
	  Select a new image to replace this one 
	</td>
</tr>
  </table>
 <br class="clear">
<div class="bar_save">
<input type="submit" value="<?=$admin_button_val[8] ?>" class="MainBtn" />
<br class="clear">
</div>
</form>
</div></ul>






<?php }elseif($_REQUEST['p'] =="img" && ADMIN_DEMO != "yes" ){ ?>
<?php 
$ServerPath=FilterPath();
$SourceFile = $ServerPath."/inc/templates/".D_TEMP."/images/";

// TRY AND AUTO CHMOD THIS
if (!is_writable($SourceFile)) {
	chmodDirectory($SourceFile,0);
}
if (is_writable($SourceFile)) {} else {print '<input class="lbOn" id="lbOnAuto" type="hidden" value="pop_chmod.php?path='.$SourceFile.'">';} 
?>

 
<ul class="form"><div class="box_body">
<form action="template.php" method="post" name="profile" enctype="multipart/form-data" onSubmit="return CheckMemberForm();">
<input name="p" type="hidden" value="img" class="hidden">
<input name="do" type="hidden" value="none" id="do" class="hidden">
<table class="widefat">
                <thead>
                  <tr> 
				  	<th scope="col"><?=$admin_table_val[18] ?></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                                 
                  </tr>
                </thead>
                <tbody>
                  <?php $totalnum=DisplayFolderImages();  ?>
                </tbody>

</table>
<input type="hidden" name="totalrows" value="<?=$totalnum ?>" class="hidden">
<br class="clear">
<div class="bar_save">
<input type="submit" value="<?=$admin_button_val[8] ?>" class="MainBtn"  onclick="ChangeOption('changeimages');"/>
<br class="clear">
</div>
</form>
</div></ul>










<?php }elseif($_REQUEST['p'] =="edit"){ ?>

<script>
function SaveEditChanges(){
	document.getElementById('editor').value=''+myCpWindow.getCode()+'';
	document.temp.submit();
}
function ChangeEditFile(filename){
	document.getElementById('file').value=''+filename+'';
	document.ChangeFileEdit.submit();
}
</script>




<?
 
if(isset($_POST['file'])){

if(isset($_POST['restorefile'])){ 
 $_POST['file']=$_POST['restorefile'];

print '<div id="messages">
		<div class="message-good" id="main-message-good">
			  <a class="dismiss-message" href="#" onclick="Effect.Fade(\'main-message-good\', { duration : 0.5 });; return false;"></a>
			 Template Changes Saved Successfully
	</div></div>';
}
 
?>
<?php   
		  $isCSS = substr($_REQUEST['file'], -3, 3);
		   $Server_Path = FilterPath();
			$DontNeedPath =0;

		if(strpos($_POST['file'], "&dd=1") != false) {	
			
			$DontNeedPath =1;
			$nFile = explode("&dd=1",$_POST['file']);
			$_POST['file']=$nFile[0];
			$path =$Server_Path.$nFile[0]; 		  


		  }elseif(isset($_POST['file']) && $_POST['file'] == "index.php"){		  
		  	$path =$Server_Path."/inc/templates/".D_TEMP."/".$_POST['file'];  


		  }elseif(isset($_POST['file']) && $_POST['file'] == "template.css"){		  
		  	$path =$Server_Path."/inc/templates/".D_TEMP."/".$_POST['file'];  


		  }elseif(isset($_POST['file']) && $_POST['file'] == "header.php" || $_POST['file'] == "footer.php" || $_POST['file'] == "menu.php" ){		  
		  	$path =FilterPath()."/inc/templates/".D_TEMP."/".$_POST['file'];	

		  }elseif(isset($_POST['file']) && $isCSS =="css"){		  
		  	$path =$Server_Path."/".$_POST['file'];  

		  }elseif(isset($_POST['file'])){		  	
			$pArray = explode("**",$_POST['file']);	
			if(!isset($pArray[1])){
		  		$path =$Server_Path."/inc/templates".$_POST['file'];		
			}else{
				//database content
				$DBFile=1;
				$path =$pArray[0]."**".$pArray[1];
			}			
		  }else{
		  	$path =FilterPath()."/inc/templates/".D_TEMP."/header.php";	
			
		  }
		 $FTPPATH = str_replace($Server_Path, "", $path);
?>
<?php 
 
$SourceFile = $path;
$path = str_replace("//","/",$path);
if(!isset($DBFile)){
	if (!is_writable($SourceFile)) {
		@chmod($SourceFile,0755);
	}
	if (is_writable($SourceFile)) {} else {print '<input class="lbOn" id="lbOnAuto" type="hidden" value="pop_chmod.php?path='.$SourceFile.'">';} 
}
?>
<?php if(ADMIN_DEMO != "yes"){ ?>
			<form method="post" action="template.php" name="temp">
			<input name="p" type="hidden" value="edit" class="hidden">
            <input name="do" type="hidden" value="update" class="hidden"> 
            <input type="hidden" name="savefile" value="<?=$path ?>" class="hidden">
			<input type="hidden" name="restorefile" value="<?=$_POST['file'] ?>" class="hidden">			 
			<input type="hidden" name="StopConfigStrip" value="1">
<?
 if(!isset($pArray[1])){
							$THISCONTENT = DisplayTemplateFile($_POST['file'], D_TEMP, $DontNeedPath);
						  }else{
							$THISCONTENT = GetPageContent($pArray[0]);
						  }	
						  ?>
			<ul class="form"><div class="box_body">
<?=displayTextArea($THISCONTENT) ?>
 
			<div class="bar_save">
			<div class="alignleft">
			<span style="font-size:12px;"><strong><?=$admin_design[12] ?></strong> <?=$FTPPATH ?> </span>
			</div>
			<br class="clear" />
			</div>
			<br class="clear" />
			<input name="update" type="submit" class="MainBtn" value="<?=$admin_button_val[8] ?>">
			</div></ul>
            </form>

<?php } ?>

 <?php }// if post ?>


<ul class="form"><div class="box_body">	

	<h1>My Pages</h1>
	<p></p>
	<table class="widefat"><thead><tr><th scope="col"></th>
	<th scope="col"><?=$admin_table_val[18] ?></th>
	<th scope="col">Page Link</th>
	<th scope="col"><?=$admin_table_val[20] ?></th>
	</tr></thead><tbody>
	<?php $totalnum =DisplayTemplatePages(3); ?>
	</tbody></table>

</div></ul>

<ul class="form"><div class="box_body">	

	<h1>Theme Globals</h1>
	<p></p>
	<table class="widefat"><thead><tr><th scope="col"></th>
	<th scope="col"><?=$admin_table_val[18] ?></th>
	<th scope="col"><?=$admin_table_val[19] ?></th>
	<th scope="col"><?=$admin_table_val[20] ?></th>
	</tr></thead><tbody>
	<?php $totalnum =DisplayTemplatePages(1); ?>
	</tbody></table>

</div></ul>


<ul class="form"><div class="box_body">	

	<h1>Layout Files</h1>
	<p></p>
	<table class="widefat"><thead><tr><th scope="col"></th>
	<th scope="col"><?=$admin_table_val[18] ?></th>
	<th scope="col"><?=$admin_table_val[19] ?></th>
	<th scope="col"><?=$admin_table_val[20] ?></th>
	</tr></thead><tbody>
	<?php $totalnum =DisplayTemplatePages(2); ?>
	</tbody></table>

</div></ul>


<ul class="form"><div class="box_body">	

	<h1>CSS Style Sheets</h1>
	<p></p>
	<table class="widefat"><thead><tr><th scope="col"></th>
	<th scope="col"><?=$admin_table_val[18] ?></th>
	<th scope="col"><?=$admin_table_val[19] ?></th>
	<th scope="col"><?=$admin_table_val[20] ?></th>
	</tr></thead><tbody>
	<?php $totalnum =DisplayTemplatePages(5); ?>
	</tbody></table>

</div></ul>

 

<form name="ChangeFileEdit" method="post" action="template.php">
<input name="file" id="file" type="hidden" value="" class="hidden">
<input name="p" type="hidden" value="edit" class="hidden">
<input name="do" type="hidden" value="none" id="do" class="hidden">
</form>
<div class="bar_save">
 

<!--<div style="display:block; background: url('inc/images/lay/sub_bg.jpg');" id="SubMenuSearch">
<select name="" style="width:130px;" onChange="ChangeEditFile(this.value);" class="input">  <option value="0">-- Layout Files --</option>	<?=DisplayTemplatePages(2) ?></select>
<select name="" style="width:130px;" onChange="ChangeEditFile(this.value);" class="input">  <option value="0">-- My Pages --</option>	<?=DisplayTemplatePages(3) ?></select>
<select name="" style="width:130px;" onChange="ChangeEditFile(this.value);" class="input">  <option value="0">-- StyleSheets --</option>	<?=DisplayTemplatePages(5) ?></select>
<select name="" style="width:130px;" onChange="ChangeEditFile(this.value);" class="input">  <option value="0">-- Config Files --</option>	<?=DisplayTemplatePages(6) ?></select>
</div><select name="" style="width:130px;" onChange="ChangeEditFile(this.value);" class="input">  <option value="0">-- Theme Globals --</option>	<?=DisplayTemplatePages(1) ?></select> -->


 
</div>
<br>


<?php }elseif($_REQUEST['p'] == "languages"){ ?>


	<ul class="form"><div class="box_body">	
		
	<form action="template.php" method="post" name="profile" onSubmit="return CheckMemberForm();">
	<input name="do" type="hidden" value="none" id="do" class="hidden">
	<input name="p" type="hidden" value="languages" class="hidden">
				  <table class="widefat">
					<thead>
					  <tr> 
						<th scope="col"></th>
						<th scope="col"><?=$admin_table_val[18] ?></th>
						<th scope="col"><?=$admin_table_val[19] ?></th>
						<th scope="col"><?=$admin_table_val[20] ?></th>
						<th scope="col"><?=$admin_table_val[21] ?></th>                    
					  </tr>
					</thead>
					<tbody>
					  <?php $totalnum =DisplayLangs(D_LANG); ?>
					</tbody>
				  </table>
	 <input type="hidden" name="totalrows" value="<?=$totalnum ?>" class="hidden">
	 
	<br class="clear">
	<div class="bar_save">
	<input type="button" value="<?=$admin_button_val[1] ?>" class="NormBtn" onClick="ca(<?=$totalnum?>)"/>
	<input type="button" value="<?=$admin_button_val[2] ?>" class="NormBtn"  onClick="ua(<?=$totalnum ?>)"/> -
	<input type="button" value="<?=$admin_button_val[5] ?>" class="MainBtn"  onclick="ChangeOption('deletelang');"/>
	<input type="button" value="<?=$admin_button_val[11] ?>" class="NormBtn"  onclick="ChangeOption('langupdate');"/>
	</div>
	</form>
	
	</div></ul>


<?php }elseif($_REQUEST['p'] == "addlanguage"){ ?>



<ul class="form"><div class="box_body">
	<form name="form1" action="template.php" method="post">
	<input type="hidden" name="do" value="langcreate" class="hidden">
	<input name="p" type="hidden" value="languages" class="hidden">	
	<li><label><?=$admin_design[17] ?>: </label>
	<div class="tip">Create a new name for your language file. Its recommended to keep it short without spaces.</div>
	<input name="name" type="text" class="input"></li>
</div></ul>
<ul class="form"><div class="box_body">
	<li><label><?=$admin_design[18] ?>:</label>
	<div class="tip">Creating a new language file to copy an existing one rename it to the name above allowing you to translate it into your new language.</div>
	<select name="file" class="input"><?=DisplayLangFile() ?></select></li>
	<li><input name="" type="submit" value="<?=$admin_button_val[8] ?>" class="MainBtn"></li>
	</form>
</div></ul>


<?php }elseif($_REQUEST['p'] == "editlanguage"){ 

if(!isset($_REQUEST['file'])){ $_REQUEST['file']=D_LANG.".php"; }
?>

<?php if(ADMIN_DEMO != "yes"){ ?>
	<script>
	function SaveEditChanges(){
	document.getElementById('editor').value=''+myCpWindow.getCode()+'';
	document.lang.submit();
	}
	</script>
	<?php 
	$ServerPath=FilterPath();
	$SourceFile = $ServerPath."/inc/langs/".$_REQUEST['file'];
	if (!is_writable($SourceFile)) {
		@chmod($SourceFile,0755);
	}
	if (is_writable($SourceFile)) {} else {print '<input class="lbOn" id="lbOnAuto" type="hidden" value="pop_chmod.php?path='.$SourceFile.'">';} 
	?>
	
	<form method="post" action="template.php" name="lang">
	<input name="p" type="hidden" value="languages" class="hidden">
	<input name="do" type="hidden" value="langedit" class="hidden">
	<input type="hidden" name="savefile" value="<?php print FilterPath()."inc/langs/".$_REQUEST['file'] ?>" class="hidden">
	<input name="editor" id="editor" type="hidden" value="" class="hidden">
<input type="hidden" value="1" name="StopConfigStrip"/>
	<textarea name="myCpWindow" wrap="VIRTUAL" class="codepress php linenumbers-on" id="myCpWindow" style="width:600px;height:500px;"><?=DisplayLAnguageFile($_REQUEST['file']);	 ?>
				</textarea>
	<br class="clear">
	<br class="clear">
	
	<div class="bar_save">
	
	<input type="button" value="<?=$admin_button_val[8] ?>" class="MainBtn" onclick="javascript:SaveEditChanges();"/>
	
	<br class="clear">
	
	</div>
	</form>


<?php } ?>

<?php }elseif($_REQUEST['p'] =="menu"){ ?>


<style>
.mgrey { background:#eee; border:1px solid #ccccc;}
.mgreen { background:#E1FFE1; border:1px solid #ccccc;}
</style>
<script>

	function ChangeMenuPage(page){

		location.href = "template.php?p=menu&t=" + page;
	}

function ChangeMenuItem(menuid){
	
	<!-- SWAP MENU ITEMS -->	
	StoreVal1 = document.getElementById('nkey'+menuid).value;
	StoreVal2 = document.getElementById('name'+menuid).value;
	
	LoID = menuid+1;
	StoreVal3 = document.getElementById('nkey'+LoID).value;
	StoreVal4 = document.getElementById('name'+LoID).value;
	
	document.getElementById('nkey'+menuid).value = StoreVal3;
	document.getElementById('name'+menuid).value = StoreVal4;
	document.getElementById('nkey'+LoID).value = StoreVal1;
	document.getElementById('name'+LoID).value = StoreVal2;
}
</script>



	 <ul class="form"><div class="box_body">	

<div class="bar_save">

	<select name="" onChange="ChangeMenuPage(this.value);" class="input" style="width:250px;">  <option value="0">-- Select Menu Bar --</option>
	<option value="1" <?php if(isset($_REQUEST['t']) && $_REQUEST['t'] ==1){  print "selected"; } ?>> Top Menu Bar</option>
	<option value="2" <?php if(isset($_REQUEST['t']) && $_REQUEST['t'] ==2){  print "selected"; } ?>> Top Sub Menu Bar</option>
	<option value="3" <?php if(isset($_REQUEST['t']) && $_REQUEST['t'] ==3){  print "selected"; } ?>> Footer Menu Bar</option>
	</select>

</div>
	
	<form name="form1" action="template.php" method="post">
	<input type="hidden" name="do" value="domenu" class="hidden">
	<input name="p" type="hidden" value="menu" class="hidden">
	<input type="hidden" value="1" name="StopConfigStrip"/>
	<table class="widefat">
	<thead>				
	<tr> 	
	<th>Menu Link</th>
	<th>Menu Caption</th>
	<th></th>
	</tr>
	</tr>
	</thead><tbody>
	<?=DisplayMenus($_REQUEST['t']) ?>
	</tbody>
	</table>
	
	<br>
	<input name="Input" type="submit" value="<?=$admin_button_val[8] ?>" class="MainBtn">
	
	
	
	
	</form>
	</div></ul>



<?php }elseif($_REQUEST['p'] =="manager"){ ?>

<?php if(ADMIN_DEMO != "yes"){ ?>
<ul class="form"><div class="box_body">
<iframe id="ListFrame" name="ListFrame" style="background:#ffffff; width:600px; height:800px;border:0px" src="inc/class/class_manager.php" scrolling="yes" frameborder="0"></iframe>
</div></ul>
<?php } ?>



<?php }elseif($_REQUEST['p'] =="terms"){ 

/**
* Page: TERMS AND CONDITIONS
*
* @version  9.0
*/

?>

<?php $msgData = DisplayTerms(); ?>
<form method="post" action="template.php" name="form1">
<input name="do" type="hidden" value="terms" class="hidden">
<input name="page" type="hidden" value="terms" class="hidden">
<input name="p" type="hidden" value="terms" class="hidden">

 
	<ul class="form"><div class="box_body"> 
	<li><label>Terms and Conditions: </label>
<div class="tip">Enter your desired website terms and conditions below.</div>
<li><textarea name="details" class="input" style="width:500px; height:300px;"><?=$msgData['value2'] ?></textarea></li>
 
<li><input type="submit" name="Submit2" value="<?=$admin_button_val[8] ?>" class="MainBtn"></li>      
	
	</div></ul>
</form>


<?php }elseif($_REQUEST['p'] =="logo"){  ?>


<form action="template.php" method="post" enctype="multipart/form-data" name="cssform">
<input type="hidden" name="do" value="builder" class="hidden">
<input name="p" type="hidden" value="logo" class="hidden">

	<ul class="form"><div class="box_body">

	<li>
	  <label>Web site Logo</label><div class="tip">Here you have the options to create a text based logo and slogan for your website. You can customize the colour scheme or choose to disable the logo.</div>
	</li>

<li><a href="javascript:void(0);" onClick="idShowHide('DivLogo1'); return false;"><img src="inc/images/16x16/add.png" align="absmiddle"> <b>Show Logo Options</b> </a> </li>

	<div id="DivLogo1" style="display:visible;">
	<table width="580"  border="0">
  <tr>
    <td width="290" bgcolor="#eeeeee"><table width="280" border="0" style="height:110px;">
          <tr>
            <td class="cs1"><strong>Web site Logo Text</strong></td>
          </tr>
          <tr>
            <td height="42"><input name="txt_logo" type="text" style="width:250px;" class="input" value="<?=TMP_LOGO ?>"> </td>
          </tr>
          <tr>
            <td class="cs2">This is the box at the top of the each page. </td>
          </tr>
        </table></td>
    <td width="280" bgcolor="#eeeeee"><table width="280"  border="0">
          <tr>
            <td class="cs1"><strong>Web site Slogan Text </strong></td>
          </tr>
          <tr>
            <td height="42" class="cs2"><input name="txt_logo_slogan" type="text" style="width:250px;" class="input" value="<?=TMP_LOGO_SLOGAN ?>"></td>
          </tr>
          <tr>
            <td class="cs2">This is the box at the top of the each page. </td>
          </tr>
        </table></td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td><table width="280"  border="0">
        <tr>
          <td width="131" class="cs1">Logo  Color </td>
          <td width="36"><input type="text" size="9" name="lc1" id="lc1" style="font-size:10px;" class="input" value="<?=TMP_LOGO_COLOR ?>"  onclick="getColor('lc1')">
          </td>
          <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('lc1')" style="cursor:pointer;"></td>
          <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_LOGO_COLOR ?>" class="b1">
              <tr>
                <td>&nbsp;</td>
              </tr>
          </table></td>
        </tr>
        <tr>
          <td height="42" colspan="4" class="cs2">This is the background for the entire website. </td>
        </tr>
        <tr>
          <td colspan="4" class="cs2">&nbsp;</td>
        </tr>
      </table></td>
    <td><table width="280"  border="0">
        <tr>
          <td width="131" class="cs1">Slogan  Color </td>
          <td width="36"><input type="text" size="9" name="lc2" id="lc2" style="font-size:10px;" class="input" value="<?=TMP_LOGO_SLOGAN_COLOR ?>" onclick="getColor('lc2')">
          </td>
          <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('lc2')" style="cursor:pointer;"></td>
          <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_LOGO_SLOGAN_COLOR ?>" class="b1">
              <tr>
                <td>&nbsp;</td>
              </tr>
          </table></td>
        </tr>
        <tr>
          <td height="42" colspan="4" class="cs2">This is the background for the entire website. </td>
        </tr>
        <tr>
          <td colspan="4" class="cs2">&nbsp;</td>
        </tr>
      </table>
     </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#eeeeee"><table width="280"  border="0" style="height:110px;">
        <tr>
          <td class="cs1"><strong>Upload My Own Logo </strong></td>
        </tr>
        <tr>
          <td><input type="file" name="LogoUpload" class="input"></td>
        </tr>
        <tr>
          <td class="cs2">This will replace any existing logo image. 350px X 80px </td>
        </tr>
      </table></td>
    <td valign="top" bgcolor="#eeeeee">      <table width="280"  border="0">
          <tr>
            <td class="cs1">Hide the website logo? <span class="cs2">
              <input type="checkbox" name="DontShowLogo" value="1" <?php if(TMP_LOGO_HIDE ==1){ print "checked"; } ?>>
            </span></td>
          </tr>
          <tr>
            <td class="cs2"><br>
              Useful if your creating a logo within the header image </td>
          </tr>
        </table>
      </td>
  </tr>
  <tr>
    <td><table width="280"  border="0">
      <tr>
        <td class="cs1"><strong>Logo Background Height </strong> </td>
      </tr>
      <tr>
        <td class="cs2"><input name="logoh" type="text" style="width:150px;" class="input" value="<?=TMP_LOGO_HEIGHT ?>">          <br>
      Adjust this value if the logo is being cut off due to a large logo image. </td>
      </tr>
    </table></td>
    <td valign="top">&nbsp;</td>
  </tr>
</table>
	</div>




	</div></ul>


	<ul class="form"><div class="box_body">

	<li><label>Website Image Logo</label>
	<div class="tip">Logo sizes are best fit at: 45px x 45px however you can use the hide logo button to disable the logo text and upload a larger logo image file with your own text on it.</div>
	</li>

	<li><a href="javascript:void(0);" onClick="idShowHide('DivLogo2'); return false;"><img src="inc/images/16x16/add.png" align="absmiddle"> <b>Show Logo Images</b> </a> </li>

	<div id="DivLogo2" style="display:none;">

	<script>
	function SetLogoImage(id){
	alert("Your logo selection has been updated.");
	document.getElementById('imgLogoIcon').value ='images/DEFAULT/LOGOS/'+id+'.png';
	document.getElementById('ClogoImage').style.display='none';
	document.getElementById('imgLogoIconDisplay').innerHTML = '<img src="../images/DEFAULT/LOGOS/'+id+'.png">';
	}
	</script>
	<style>
	
	.logoimages1 { width:550px;  }
	.logoimages1 li {  width:90px; height:70px;  margin:5px; float:right;}
	</style>
	<div style="border:1px solid #ccc; padding:5px; background:#eee; width:580px;  height:300px; margin-left:10px; margin-top:5px; overflow:auto">
	<ul class="logoimages1">
	<?	$i=1;	while($i < 53){	?>

	<li style="float:right;"><a href="#" onClick="SetLogoImage('<?=$i ?>');"><img src="../images/DEFAULT/LOGOS/<?=$i ?>.png" id="img_<?=$i ?>" style="float:left;"></a></li>

	<?php $i++; } ?>

	</ul>
	</div>
	<input name="txt_logo_image" type="hidden" id="imgLogoIcon" value="<?=TMP_LOGO_ICON ?>">
	<br><li><label><input type="checkbox" onClick="SetLogoImage('none');"> Remove Logo Icon</label></li>
	</div>


	<?php if(TMP_LOGO_ICON !=""){ ?>
	<br><div class="bar_save" style="margin-left:10px; padding:10px;"><strong>&nbsp;Current Logo Image </strong></div><br>
	<?php  
		if(substr(TMP_LOGO_ICON,0,4) =="http"){
		  print "<img src='".TMP_LOGO_ICON."' id='ClogoImage'>";
		}else{
			print "<img src='../".TMP_LOGO_ICON."' id='ClogoImage'>";
		}
	?>
	
	<?php } ?>
	<div id="imgLogoIconDisplay"> &nbsp; </div>

	</div></ul>



	<div class="bar_save">
	
		<input name="button" type="submit" value="Save Changes" class="MainBtn"> 
		<br class="clear">
	</div>
</form>

   	<div id="plugin" onmousedown="HSVslide('drag','plugin',event)" style="TOP: 58px; Z-INDEX: 20;">
	<div id="plugCUR"></div><div id="plugHEX" onmousedown="stop=0; setTimeout('stop=1',100);">FFFFFF</div>
	<div id="plugCLOSE" onClick="getColor('c1');">X</div><br>
	<div id="SV" onmousedown="HSVslide('SVslide','plugin',event)" title="Saturation + Value">
	 <div id="SVslide" style="TOP: -4px; LEFT: -4px;"><br /></div>
	</div>
	<form id="H" onmousedown="HSVslide('Hslide','plugin',event)" title="Hue">
	 <div id="Hslide" style="TOP: -7px; LEFT: -8px;"><br /></div>
	 <div id="Hmodel"></div>
	</form>
   </div>
  	<input type="text" value="ColourPickIder" id="ColourPickIder" style="display:none;">
	<script type="text/javascript">
	loadSV();
	HSVupdate({H:0, S:0, V:20});
	$S('plugin').left=($('lc2').offsetLeft+35)+'px';
	$S('plugin').top=($('lc2').offsetTop+35)+'px';		 
	$S('plugin').display='none';
	
	</script>
	

<?php }elseif($_REQUEST['p'] =="color"){  ?>


<form action="template.php" method="post" enctype="multipart/form-data" name="cssform">
<input type="hidden" name="do" value="builder" class="hidden">
<input name="p" type="hidden" value="color" class="hidden">
 
<ul class="form"><div class="box_body">

<li><label>Preset Layout Colors</label>
<div class="tip">Listed below are a selection of predesigned colour schemes. To use any of these colour schemes simply check the box directly under the colour scheme of your choice.</div>
</li>
<li><a href="javascript:void(0);" onClick="idShowHide('DivColours1'); return false;"><img src="inc/images/16x16/add.png" align="absmiddle"> <b>Show Colour Schemes</b> </a> </li>

	<div id="DivColours1" style="display:none;">
	<li>
	<table width="580"  border="0">
	  <tr>
		<td width="145"><img src="inc/images/theme/s1.gif" width="140" height="55" class="c3"></td>
		<td width="145"><img src="inc/images/theme/s2.gif" width="140" height="55" class="c3"></td>
		<td width="145"><img src="inc/images/theme/s3.gif" width="140" height="55" class="c3"></td>
		<td width="147"><img src="inc/images/theme/s4.gif" width="140" height="55" class="c3"></td>
	  </tr>
	  <tr>
		<td><input name="p1" type="radio" value="2">
	
	<input name="pa2" type="hidden" value="#5679AC">
	<input name="pb2" type="hidden" value="#6C8AB7">
	<input name="pc2" type="hidden" value="#CFD8E6">
	<input name="pd2" type="hidden" value="#EBEFEF">
	<input name="pe2" type="hidden" value="#5679AC">
	<input name="pf2" type="hidden" value="#5679AC"></td>
		<td><input name="p1" type="radio" value="3">
	
	<input name="pa3" type="hidden" value="#509F00">
	<input name="pb3" type="hidden" value="#336600">
	<input name="pc3" type="hidden" value="#A9DB8A">
	<input name="pd3" type="hidden" value="#E9FCDD">
	<input name="pe3" type="hidden" value="#000000">
	<input name="pf3" type="hidden" value="#000000"></td>
		<td><input name="p1" type="radio" value="4">
	
	<input name="pa4" type="hidden" value="#403562">
	<input name="pb4" type="hidden" value="#2D2545">
	<input name="pc4" type="hidden" value="#E0D6FC">
	<input name="pd4" type="hidden" value="#FAF3FF">
	<input name="pe4" type="hidden" value="#000000">
	<input name="pf4" type="hidden" value="#000000"></td>
		<td><input name="p1" type="radio" value="5">
	
	<input name="pa5" type="hidden" value="#B22222">
	<input name="pb5" type="hidden" value="#7D1818">
	<input name="pc5" type="hidden" value="#FF9898">
	<input name="pd5" type="hidden" value="#FEE3E3">
	<input name="pe5" type="hidden" value="#000000">
	<input name="pf5" type="hidden" value="#000000"></td>
	  </tr>
	  <tr>
		<td><img src="inc/images/theme/s5.gif" width="140" height="55" class="c3"></td>
		<td><img src="inc/images/theme/s6.gif" width="140" height="55" class="c3"></td>
		<td><img src="inc/images/theme/s7.gif" width="140" height="55" class="c3"></td>
		<td><img src="inc/images/theme/s8.gif" width="140" height="55" class="c3"></td>
	  </tr>
	  <tr>
		<td><input name="p1" type="radio" value="6">
	
	<input name="pa6" type="hidden" value="#333333">
	<input name="pb6" type="hidden" value="#242424">
	<input name="pc6" type="hidden" value="#CCCCCC">
	<input name="pd6" type="hidden" value="#EFE9E9">
	<input name="pe6" type="hidden" value="#000000">
	<input name="pf6" type="hidden" value="#000000"></td>
		<td><input name="p1" type="radio" value="7">
	
	<input name="pa7" type="hidden" value="#CE5E06">
	<input name="pb7" type="hidden" value="#904204">
	<input name="pc7" type="hidden" value="#FFBA83">
	<input name="pd7" type="hidden" value="#FCEDE2">
	<input name="pe7" type="hidden" value="#000000">
	<input name="pf7" type="hidden" value="#000000"></td>
		<td><input name="p1" type="radio" value="8">
	
	<input name="pa8" type="hidden" value="#000000">
	<input name="pb8" type="hidden" value="#00FF00">
	<input name="pc8" type="hidden" value="#FF0000">
	<input name="pd8" type="hidden" value="#E8E8EF">
	<input name="pe8" type="hidden" value="#000000">
	<input name="pf8" type="hidden" value="#000000"></td>
		<td><input name="p1" type="radio" value="9">
	
	<input name="pa9" type="hidden" value="#D1E2AE">
	<input name="pb9" type="hidden" value="#ADDAE2">
	<input name="pc9" type="hidden" value="#F6F6AD">
	<input name="pd9" type="hidden" value="#FFF4F4">
	<input name="pe9" type="hidden" value="#000000">
	<input name="pf9" type="hidden" value="#000000"></td>
	  </tr>
	</table>
	
	</li>
	<br><hr><br>
	<li><label><input name="p1" type="radio" value="1" checked> Do not use a colour scheme</label>
	<div class="tip"> Select this option if you do not wish to use any of the colour schemes above.</div>
	</li>
</div>

</div></ul>

<ul class="form"><div class="box_body"><li><label>Choose Your Own</label>
<div class="tip">Use the options below to create your own colour scheme for your website.</div>

</li>
<li><a href="javascript:void(0);" onClick="idShowHide('DivColours2'); return false;"><img src="inc/images/16x16/add.png" align="absmiddle"> <b>Show Colour Options</b> </a> </li>

	<div id="DivColours2" style="display:none;">

<!--<li><label><input name="tmp_default" type="checkbox" value="1" checked>  Keep Current Styles</label><div class="tip">Uncheck this box if you would like to edit your current colour scheme. </div>-->

<table width="590"  border="0">
  <tr>
    <td style="padding:5px; background:#eeeeee;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Background</td>
            <td width="36"><input name="c1" id="c1" type="text" style="font-size:10px; width:80px" size="9" class="input" onclick="getColor('c1')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c1')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_BACKGROUND ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the background for the entire website. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2"><img src="inc/images/icons/resultset_next.png" width="16" height="16" align="absmiddle"> <a href="javascript:void(0);" onClick="PreviewWin('inc/pops/pop_image.php?tt=1'); return false;">Upload an image</a> <?php if(TMP_BACKGROUND_IMG !=""){ ?><br>  <img src="inc/images/icons/yes.png" align="absmiddle"> Image Attached <?php } ?></td>
          </tr>
        </table></td>
    <td style="padding:5px; background:#eeeeee;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Header Colour </td>
            <td width="36"><input type="text" size="9" name="c2" id="c2" style="font-size:10px; width:80px" class="input" onclick="getColor('c2')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c2')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_FOR_1 ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the section where the logo is located. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table></td>
  </tr>
  <tr>
    <td style="padding:5px;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Menu Bar</td>
            <td width="36"><input type="text" size="9" name="c3" id="c3" style="font-size:10px; width:80px" class="input" onclick="getColor('c3')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c3')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_FOR_2 ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the top menu bar.</td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table></td>
    <td valign="top" style="padding:5px;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Inner Content </td>
            <td width="36"><input type="text" size="9" name="c4" id="c4" style="font-size:10px; width:80px" class="input" onclick="getColor('c4')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c4')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_FOR_3 ?>" class="b1">
                <tr>
                  <td style="width:16px; height:16px;">&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the background for the entire website. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table></td>
  </tr>
  <tr>
    <td style="padding:5px; background:#eeeeee;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Menu Links</td>
            <td width="36"><input type="text" size="9" name="c5" id="c5" style="font-size:10px; width:80px" class="input" onclick="getColor('c5')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c5')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_LINK_MENU ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the menu link colour. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table></td>
    <td style="padding:5px; background:#eeeeee;"><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Links</td>
            <td width="36"><input type="text" size="9" name="c6" id="c6" style="font-size:10px; width:80px" class="input" onclick="getColor('c6')">
            </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c6')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_LINK ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the entire website link colour scheme. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table>
      </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    </tr>
  <tr>
    <td><table width="280"  border="0">
          <tr>
            <td width="131" class="cs1">Page Header </td>
            <td width="36"><span class="cs2">
              <input type="text" size="9" name="c7" id="c7" style="font-size:10px; width:80px" class="input" onClick="getColor('c7')">
            </span> </td>
            <td width="32"><img width="15" height="13" border="0" src="inc/images/icons/colourselect.gif" onclick="getColor('c7')" style="cursor:pointer;"></td>
            <td width="22" valign="top"><table width="16" height="16"  border="0" cellpadding="0" cellspacing="0" bgcolor="<?=TMP_PAGE_HEAD ?>" class="b1">
                <tr>
                  <td>&nbsp;</td>
                </tr>
            </table></td>
          </tr>
          <tr>
            <td height="42" colspan="4" class="cs2">This is the box at the top
               
              of the each page. </td>
          </tr>
          <tr>
            <td colspan="4" class="cs2">&nbsp;</td>
          </tr>
        </table></td>
    <td>&nbsp;</td>
  </tr>
</table>

</div>

</div></ul>

<ul class="form"><div class="box_body"> 
</li>

<li><label><input name="tmp_reset" type="checkbox" value="1"> Reset To Default Styles</label><div class="tip">Check this box if you would like to reset the template colour scheme back to the template defauls.</div></li>

</div></ul>

<div class="bar_save">

<input name="button2" type="submit"  value="Submit" class="MainBtn">
 <br class="clear">
</div>
	
</form>




   	<div id="plugin" onmousedown="HSVslide('drag','plugin',event)" style="TOP: 58px; Z-INDEX: 20;">
	<div id="plugCUR"></div><div id="plugHEX" onmousedown="stop=0; setTimeout('stop=1',100);">FFFFFF</div>
	<div id="plugCLOSE" onClick="getColor('c1');">X</div><br>
	<div id="SV" onmousedown="HSVslide('SVslide','plugin',event)" title="Saturation + Value">
	 <div id="SVslide" style="TOP: -4px; LEFT: -4px;"><br /></div>
	</div>
	<form id="H" onmousedown="HSVslide('Hslide','plugin',event)" title="Hue">
	 <div id="Hslide" style="TOP: -7px; LEFT: -8px;"><br /></div>
	 <div id="Hmodel"></div>
	</form>
   </div>
  	<input type="text" value="ColourPickIder" id="ColourPickIder" style="display:none;">
	<script type="text/javascript">
	loadSV();
	HSVupdate({H:0, S:0, V:20});
	$S('plugin').left=($('c1').offsetLeft+35)+'px';
	$S('plugin').top=($('c1').offsetTop+35)+'px';		 
	$S('plugin').display='none';
	
	</script>

 

<?php }elseif($_REQUEST['p'] == "newpage"){ ?>

	<script>
	function SaveEditChanges(){
	document.getElementById('editor').value=''+myCpWindow.getCode()+'';
	document.lang.submit();
	}
	</script>
<form action="template.php" method="post" name="lang">
<input type="hidden" name="do" value="create" class="hidden">
<input type="hidden" name="p" value="edit" class="hidden">
<input type="hidden" name="editor" id="editor" value="" class="hidden">
<input type="hidden" value="1" name="StopConfigStrip"/>

<ul class="form">

<div class="box_body">	 
<li><label>Page Name: </label><input name="name" type="text" size="30" maxlength="15" class="input">
<div class="tip">This will be used in your page link so keep it short without spaces.</div>
</li>
 
<?=displayTextArea("") ?>

<br><br>
<div class="bar_save">

<input name="button2" type="submit"  value="Save Page" class="MainBtn">
 <br class="clear">
</div>
</form>

</div> </ul>


<?php }elseif($_REQUEST['p'] == "text"){ ?>


<form action="template.php" method="post">
<input type="hidden" name="do" value="builder" class="hidden">
<input name="p" type="hidden" value="text" class="hidden">
<input name="StopConfigStrip" type="hidden" value="StopConfigStrip" class="hidden">
	<ul class="form"><div class="box_body">
	
	<li><label>Welcome Title</label><input name="txt1" type="text" value="<?=TMP_TXT_1 ?>" size="75" class="input"></li>
	<li><label>Welcome Subtitle</label><input name="txt2" type="text" value="<?=TMP_TXT_2 ?>" size="75" class="input"></li>

	</div></ul><ul class="form"><div class="box_body">

	<li><label>Introduction Title</label><input name="txt3" type="text" value="<?=TMP_TXT_3 ?>" size="75" class="input"></li>
	<li><label>Introduction Subtitle</label>
	  <textarea name="txt4" cols="75" class="input" style="width:550px; height:100px;"><?=TMP_TXT_4 ?></textarea>
	</li>

	</div></ul><ul class="form"><div class="box_body">

	<li><label>Introduction Title Extra</label><input name="txt5" type="text" value="<?=TMP_TXT_5 ?>" size="75" class="input"></li>
	<li><label>Introduction Subtitle Extra</label>
	  <textarea name="txt6" cols="75" class="input" style="width:550px; height:100px;"><?=TMP_TXT_6 ?></textarea>
	</li>

	</div></ul>


	<div class="bar_save">
	<input name="Submit" type="submit" value="Save Changes" class="MainBtn"> 
	</div>

</form>

<br><br><br>
<div class="bar_save">
<form action="template.php" method="post">
<input type="hidden" name="do" value="reset" class="hidden">
<input name="p" type="hidden" value="text" class="hidden">
<b>Reset Fields</b><br>
<p>If you have problems editing these fields click this button to reset them back to the software defaults.</p>
<input name="Submit" type="submit" value="Reset All Fields" class="MainBtn"> 
</form>
</div>	
<?php } ?>